baseURL = "https://immersionteambuilding.ai/"
languageCode = "en-us"
title = "Immersion Teambuilding"
theme = "lightbi-hugo"

# Metadata for SEO and Social Media
author = "Wolf"
description = "Site hosting Teambuilding company, teambuilding through virtual tabletop rpg games."
keywords = ["teambuilding", "training", "lightbi-hugo"]

# Content Settings
paginate = 10
summaryLength = 150
defaultContentLanguage = "en"
enableRobotsTXT = true

# Permalinks
[permalinks]
posts = "/blog/:slug/"

# Taxonomies
[taxonomies]
category = "categories"
tag = "tags"

# Social Media Links
[social]
twitter = "https://twitter.com/YourTwitterHandle"
github = "https://github.com/WolfLycanorcant"
linkedin = "https://linkedin.com/in/YourLinkedInProfile"

# Sitemap Configuration
[sitemap]
changefreq = "weekly"
priority = 0.5

# Enable Syntax Highlighting
[markup]
[markup.highlight]
style = "monokai"
lineNos = true
noClasses = false
